# Generated by Django 4.1.4 on 2023-02-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_vendorreviews_liked_by_alter_vendorreviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorreviews',
            name='liked_by',
        ),
    ]
