# Generated by Django 4.1.4 on 2023-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('vendor', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('vendor', 'food_title')},
        ),
    ]
