# Generated by Django 4.1.4 on 2023-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_fooditem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
